---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthify-org
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthifu-org
  template:
    metadata:
      labels:
        app: healthify-org
    spec:
      containers:
      - name: healthify-org
        image: sark112/healthify-org:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: healthify-org-service
spec:
  selector:
    app: healthify-org
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
