name: Trivy Image Scan Workflow

on:
  push:
    branches: [ main ]
  
jobs:
    build:
      name: Docker Image Scan
      runs-on: self-hosted
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Pull the Docker image From DockerHub
          run: docker pull sark112/react-aws-eks-github-actions:latest

  
        - name: Trivy image scan
          run: trivy image sark112/react-aws-eks-github-actions:latest
  
